FROM jetty:9-jdk8-openjdk

USER root
RUN apt-get -y update && \
    apt-get install -y maven

USER jetty
RUN git clone --recursive https://github.com/eea/geonetwork-eea.git

RUN cd geonetwork-eea && \
    mvn clean install -DskipTests
RUN cd geonetwork-eea/web && \
    mvn package  -DskipTests -Penv-catalogue
